[package]
name = "codespawn"
version = "0.1.0"
license = "MIT/Apache-2.0"
authors = ["Krzysztof Kondrak <krzysztof.kondrak@gmail.com>"]
repository = "https://github.com/kondrak/codespawn"
homepage = "https://github.com/kondrak/codespawn"

[dependencies]
